name: dedavid
favicon: null
layout_spectrum: 0.8634538839105517
typography_spectrum: 0.07871799729764462
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.28570949425920844
  lightness: 0.29302811110392213
  saturation: 0.13051224639639258
  rhythmicContrast: 0.14747906639240682
purpose: []
