name: dedavid
favicon: null
layout_spectrum: 0.8634538839105517
typography_spectrum: 0.07871799729764462
title: de David
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a6d2fa'
    - '#0a0c0d'
    - '#fffffd'
    - '#7f9db9'
    - '#b84d30'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.13051224639639258
  rhythmicContrast: 0.25
purpose: []
